# Generated by Django 3.1.5 on 2021-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('startbid', models.IntegerField()),
                ('imgurl', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
