# Generated by Django 3.1.5 on 2021-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
