# Generated by Django 3.1.5 on 2021-01-22 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210122_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_date', models.DateTimeField(default=datetime.datetime(2021, 1, 22, 11, 29, 47, 978521, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_for_product_biddet', to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='auctions.product')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 11, 29, 47, 978521, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
