# Generated by Django 3.1.5 on 2021-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startbid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
