# Generated by Django 3.1.5 on 2021-01-22 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210122_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='unknow', max_length=100)),
                ('watchlist', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 13, 45, 20, 791256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 13, 45, 20, 790257, tzinfo=utc)),
        ),
    ]
