# Generated by Django 3.1.5 on 2021-01-22 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210122_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 15, 2, 30, 841401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 15, 2, 30, 840401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.URLField(default='auctions/no_image.png'),
        ),
    ]
