# Generated by Django 3.1.5 on 2021-01-23 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210123_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 8, 58, 101120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 8, 58, 100118, tzinfo=utc)),
        ),
    ]
